# Automatially run copy-from-linux-branch.sh on branches and create PR for redfs.
name: Sync to redfs repo
on:
  # Triggers the workflow on pull request merged.
  pull_request:
    branches: [ "redfs-*" ]
    types: [ "closed" ]

jobs:
  create-redfs-pr:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      # Checks-out to a different directory to avoid following checkout removing it.
      - name: Checkout Linux source repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 10
          path: linux

      - name: Generate commit message
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
          HEAD_SHA: ${{ github.event.pull_request.head.sha }}
          REPO_NAME: ${{ github.repository }}
          BRANCH_NAME: ${{ github.ref_name }}
        run: |
          pushd linux
          echo -e "Sync with $REPO_NAME branch $BRANCH_NAME\n" > ../commit.msg
          echo -e "Sync with $REPO_NAME branch $BRANCH_NAME PR $PR_NUMBER" >> ../commit.msg
          echo -e "$PR_TITLE\n" >> ../commit.msg
          echo -e "(commit: ${{ github.sha }})\n" >> ../commit.msg
          echo "Getting git log $BASE_SHA..$HEAD_SHA"
          RET=0
          git log --format="- %h %s" $BASE_SHA..$HEAD_SHA >> ../commit.msg || RET=$?
          if [ $RET -ne 0 ]; then
            echo "Failed to get git log with range, try to get log with single commit (too many commits?)."
            git log --format="- %s" $HEAD_SHA >> ../commit.msg || RET=$?
            if [ $RET -ne 0 ]; then
              echo "Failed to get git log, exit with error."
              exit 1
            fi
          fi
          echo "Generated commit message:"
          cat ../commit.msg
          popd

      - name: Try to checkout redfs branch sync-${{ github.ref_name }} if it exists
        uses: actions/checkout@v6
        id: try-checkout
        continue-on-error: true
        with:
          repository: DDNStorage/redfs
          ref: sync-${{ github.ref_name }}
          fetch-depth: 0
          path: redfs
          token: ${{ secrets.REDFS_TOKEN }}

      - name: Fallback to checkout redfs branch main
        if: steps.try-checkout.outcome == 'failure'
        uses: actions/checkout@v6
        with:
          repository: DDNStorage/redfs
          ref: main
          fetch-depth: 0
          path: redfs
          token: ${{ secrets.REDFS_TOKEN }}

      - name: Initialize git
        run: |
          git config --global user.name "DDNStorage RED Workflow"
          git config --global user.email "red@ddn.com"

      - name: Create tracking branch based on main
        if: steps.try-checkout.outcome == 'failure'
        run: |
          pushd redfs
          git checkout -b sync-${{ github.ref_name }}
          popd

      - name: Generate PR for redfs
        run: |
          declare -A MAP
          MAP["redfs-rhel9_4-427.42.1"]="5.14.0-427.42.1.el9_4"
          MAP["redfs-rhel9_5-503.40.1"]="5.14.0-503.40.1.el9_5"
          MAP["redfs-rhel9_6-570.12.1"]="5.14.0-570.12.1.el9_6"
          MAP["redfs-rhel10_0"]="6.12.0"
          MAP["redfs-ubuntu-noble-6.8.0-58.60"]="6.8.0-58.60.ubuntu"
          MAP["redfs-ubuntu-hwe-6.17.0-16.16-24.04.1"]="6.17.0-16.16.ubuntu"
          kerver=${MAP["${{ github.ref_name }}"]}
          if [ -z ${kerver} ]; then
            echo "Cannot find target kernel version"
            exit 1
          fi
          pushd redfs
          ./copy-from-linux-branch.sh $GITHUB_WORKSPACE/linux ${kerver}
          git add src/$kerver
          RET=0
          echo "Committing changes with message:"
          cat ../commit.msg
          git commit -F ../commit.msg 2> ../commit.log || RET=$?;
          if [ -s ../commit.log ]; then
            echo "Error detcted in commit:"
            cat ../commit.log
            exit 1
          elif [ $RET -eq 0 ]; then
            echo "Done. Push the code to remote:"
            git push origin sync-${{ github.ref_name }} 2> ../push.log ||:
          else
            echo "No changes to existed codes. Still try with PR."
          fi
          if [ -s ../push.log ]; then
            echo "Message detected in push:"
            cat ../push.log
          fi
          gh pr create --base main --fill || RET=$?
          if [ $RET -eq 1 ]; then
            echo "No pending changes for PR, returning $RET."
          fi
          popd
        env:
          GH_TOKEN: ${{ secrets.REDFS_TOKEN }}

